# Originally contributed by @rbuffat to Toblerity/Fiona
# https://github.com/Toblerity/Shapely/blob/master/.travis.yml
dist: xenial
group: travis_latest
language: python
sudo: false

stages:
  - lint
  - test

cache:
  directories:
    - $GDALINST
    - ~/.cache/pip
env:
  global:
    - PIP_WHEEL_DIR=$HOME/.cache/pip/wheels
    - PIP_FIND_LINKS=file://$HOME/.cache/pip/wheels
    - GDALINST=$HOME/gdalinstall
    - GDALBUILD=$HOME/gdalbuild

matrix:
  include:
    - python: 2.7
      stage: lint
      env: TOXENV=lint
      addons: skip
      before_install: skip
      after_success: skip

    - python: 2.7
      stage: test
      env:
        - TOXENV=py27-gdal2.3.3
        - GDALVERSION=2.3.3
    - python: 3.6
      stage: test
      env:
        - TOXENV=py36-gdal2.3.3
        - GDALVERSION=2.3.3
    - python: 3.7
      stage: test
      env:
        - TOXENV=py37-gdal2.3.3
        - GDALVERSION=2.3.3

    - python: 2.7
      stage: test
      env:
        - TOXENV=py27-gdal2.4.0
        - GDALVERSION=2.4.0
    - python: 3.6
      stage: test
      env:
        - TOXENV=py36-gdal2.4.0
        - GDALVERSION=2.4.0
    - python: 3.7
      stage: test
      env:
        - TOXENV=py37-gdal2.4.0
        - GDALVERSION=2.4.0

addons:
  apt:
    packages:
    - gdal-bin
    - libproj-dev
    - libhdf5-serial-dev
    - libpng12-dev
    - libgdal-dev
    - libatlas-dev
    - libatlas-base-dev
    - gfortran

before_install:
  - . ./.travis/install_gdal.sh
  - export PATH=$GDALINST/gdal-$GDALVERSION/bin:$PATH
  - export LD_LIBRARY_PATH=$GDALINST/gdal-$GDALVERSION/lib:$LD_LIBRARY_PATH
  - export GDAL_DATA=$GDALINST/gdal-$GDALVERSION/share/gdal
  - export PROJ_LIB=/usr/share/proj
  - export CPLUS_INCLUDE_PATH=/usr/include/gdal
  - export C_INCLUDE_PATH=/usr/include/gdal
  - gdal-config --version
  - "if [ $(gdal-config --version) == \"$GDALVERSION\" ]; then echo \"Using gdal $GDALVERSION\"; else echo \"NOT using gdal $GDALVERSION as expected; aborting\"; exit 1; fi"
install:
  - pip install -U pip tox coveralls
script:
  - tox
after_success:
  - coveralls
